# Generated by Django 4.2.11 on 2024-03-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_name_movie_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="identifier",
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
